# Generated by Django 6.0.3 on 2026-04-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('customer', 'Customer'), ('receptionist', 'Receptionist'), ('manager', 'Manager'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
