"""
hotel_management/flask_auth_backend.py
Django authentication backend that validates sessions stored by the
Flask auth service in the shared PostgreSQL database.

Integration approach: SHARED DATABASE
- Flask writes sessions to `auth_sessions` table.
- Django reads from the same table directly — zero HTTP overhead per request.
- No JWT. No token in localStorage. Secure HttpOnly cookie only.

Setup (settings.py)
-------------------
AUTHENTICATION_BACKENDS = [
    "hotel_management.flask_auth_backend.FlaskSessionAuthBackend",
    "django.contrib.auth.backends.ModelBackend",   # keep for /admin
]

FLASK_AUTH_DB_URL = "postgresql://postgres:postgres@localhost:5432/hotel_db"
# Must match Flask's SESSION_IDLE_TIMEOUT (minutes)
FLASK_SESSION_IDLE_MINUTES = 30
# INTERNAL_SERVICE_TOKEN is NOT set here \u2014 it is auto-generated by the Flask
# service and stored in the auth_app_secrets DB table. Django reads it from
# the same table via flask_session_middleware._load_internal_token().
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import TYPE_CHECKING, Any

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.backends import BaseBackend

if TYPE_CHECKING:
    from django.contrib.auth.models import AbstractBaseUser
    from django.http import HttpRequest

User = get_user_model()


class FlaskSessionAuthBackend(BaseBackend):
    """
    Reads `auth_sessions` + `auth_users` written by the Flask service.

    authenticate(request, session_id=<uuid_string>)
        → returns a Django User (matched by email) or None.

    The Django FlaskSessionMiddleware calls this on every request.
    """

    # ------------------------------------------------------------------
    # DB helper — lazy SQLAlchemy engine (avoid import at module level)
    # ------------------------------------------------------------------

    _engine: Any = None

    def _get_engine(self):
        if self.__class__._engine is not None:
            return self.__class__._engine

        try:
            from sqlalchemy import create_engine

            db_url = getattr(
                settings,
                "FLASK_AUTH_DB_URL",
                self._django_db_url(),
            )
            self.__class__._engine = create_engine(
                db_url,
                pool_pre_ping=True,
                pool_recycle=300,
            )
        except ImportError:
            return None

        return self.__class__._engine

    @staticmethod
    def _django_db_url() -> str:
        """Build a SQLAlchemy URL from Django's DATABASES['default']."""
        d = settings.DATABASES["default"]
        return (
            f"postgresql://{d['USER']}:{d['PASSWORD']}"
            f"@{d.get('HOST', 'localhost')}:{d.get('PORT', '5432')}/{d['NAME']}"
        )

    # ------------------------------------------------------------------
    # Session lookup
    # ------------------------------------------------------------------

    def _fetch_session(self, session_id: str) -> dict | None:
        engine = self._get_engine()
        if engine is None:
            return None

        try:
            from sqlalchemy import text

            idle_timeout = timedelta(
                minutes=getattr(settings, "FLASK_SESSION_IDLE_MINUTES", 30)
            )
            now = datetime.now(timezone.utc)

            with engine.connect() as conn:
                row = conn.execute(
                    text(
                        """
                        SELECT
                            s.user_id, s.role, s.tenant_id, s.branch_id,
                            s.is_fresh_auth, s.fresh_until,
                            s.expires_at, s.last_active,
                            u.email
                        FROM auth_sessions s
                        JOIN auth_users u ON u.id = s.user_id
                        WHERE s.id = :sid
                          AND s.is_valid = true
                          AND u.is_active = true
                        """
                    ),
                    {"sid": session_id},
                ).fetchone()

            if not row:
                return None

            def _aware(dt: datetime) -> datetime:
                return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)

            expires_at = _aware(row.expires_at)
            last_active = _aware(row.last_active)

            if now > expires_at:
                # Hard-invalidate the expired row in-place so it cannot be replayed
                with engine.begin() as wconn:
                    wconn.execute(
                        text(
                            "UPDATE auth_sessions "
                            "SET is_valid = false, csrf_token = '' "
                            "WHERE id = :sid"
                        ),
                        {"sid": session_id},
                    )
                return None
            if now > last_active + idle_timeout:
                # Hard-invalidate the idle-timed-out row
                with engine.begin() as wconn:
                    wconn.execute(
                        text(
                            "UPDATE auth_sessions "
                            "SET is_valid = false, csrf_token = '' "
                            "WHERE id = :sid"
                        ),
                        {"sid": session_id},
                    )
                return None

            fresh_until = _aware(row.fresh_until) if row.fresh_until else None

            # Mirror exactly the same freshness logic used by Flask's is_session_fresh():
            # is_fresh_auth=True AND fresh_until is set AND fresh_until has not passed.
            # WITHOUT this check, the flag stays True forever after login and
            # @flask_fresh_required never redirects to the reauth gate.
            is_actually_fresh = (
                bool(row.is_fresh_auth)
                and fresh_until is not None
                and now < fresh_until
            )

            return {
                "user_id": str(row.user_id),
                "email": row.email,
                "role": row.role,
                "tenant_id": str(row.tenant_id) if row.tenant_id else None,
                "branch_id": str(row.branch_id) if row.branch_id else None,
                "is_fresh_auth": is_actually_fresh,
                "fresh_until": fresh_until.isoformat() if fresh_until else None,
            }

        except Exception:
            # Never crash Django because the Flask auth DB is unavailable
            return None

    # ------------------------------------------------------------------
    # Django backend interface
    # ------------------------------------------------------------------

    def authenticate(
        self,
        request: "HttpRequest",
        session_id: str | None = None,
        **kwargs,
    ) -> "AbstractBaseUser | None":
        if not session_id:
            return None

        flask_data = self._fetch_session(session_id)
        if not flask_data:
            return None

        try:
            django_user = User.objects.get(email=flask_data["email"])
        except User.DoesNotExist:
            # Auto-provision a thin Django user for Flask-authenticated accounts.
            # Password auth is fully disabled on this Django side record.
            username_base = flask_data["email"].split("@")[0][:145]
            username = username_base
            suffix = 1
            while User.objects.filter(username=username).exists():
                username = f"{username_base}{suffix}"
                suffix += 1

            django_user = User(
                username=username,
                email=flask_data["email"],
                is_active=True,
            )
            django_user.set_unusable_password()
            django_user.save()

        # Attach Flask session data as transient attributes so views can use it
        django_user.flask_role = flask_data["role"]
        django_user.flask_tenant_id = flask_data["tenant_id"]
        django_user.flask_branch_id = flask_data["branch_id"]
        django_user.flask_is_fresh = flask_data["is_fresh_auth"]
        django_user.flask_fresh_until = flask_data["fresh_until"]
        return django_user

    def get_user(self, user_id):
        try:
            return User.objects.get(pk=user_id)
        except User.DoesNotExist:
            return None
